### ISSUE TITLE
Incohérence entre le titre de la page Membres et le titre du lien

### ISSUE THREAD

**Issue by rspt** [SimonNtz/DAL_web#5]
Dans le menu il y a un lien qui s'intitule "Comités" et qui redirige vers un URL "/membres/".

Est-ce qu'on garde "Comité" ou "Membres"?

**Comment by SimonNtz** [comment]
Mettons "Membres" car on risque surement de rajouter des photos de membres qui font pas parti du comité

**Comment by rspt** [comment]
Ok!

**Comment by rspt** [comment]
Fixé
