### ISSUE TITLE
Est-ce que le contenu de la page Activités est toujours valable???

### ISSUE THREAD

**Issue by rspt** [SimonNtz/DAL_web#6]
https://www.dal-geneve.ch/activites/

**Comment by SimonNtz** [comment]
Oui pour l'instant ça va

**Comment by rspt** [comment]
C'est du copié-coller d'un site que j'avais fait, du coup je doute que ce soit bon ;)

**Comment by SimonNtz** [comment]
Haha juste c'était histoire d'afficher du texte facilement  depuis des .doc. Si t'as une autre référence hésite pas!

**Comment by rspt** [comment]
Fixé. J'ai ajouté la liste des activités (la même que sur la homepage)
